//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Image1 = new HashSet<Image>();
            this.Property = new HashSet<Property>();
            this.UserProduct = new HashSet<UserProduct>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    
        public virtual ICollection<Image> Image1 { get; set; }
        public virtual ICollection<Property> Property { get; set; }
        public virtual ICollection<UserProduct> UserProduct { get; set; }
    }
}
