//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProduct
    {
        public UserProduct()
        {
            this.Quote = new HashSet<Quote>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string AspNetUserId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<Quote> Quote { get; set; }
    }
}
